name 'ice_motd'
maintainer 'Mauro Oddi'
maintainer_email 'mauro.oddi@progress.com'
license 'All Rights Reserved'
description 'Installs/Configures ice_motd'
version '0.1.0'
chef_version '>= 16.0'
issues_url 'https://github.com/mauroseb/ice_motd/issues'
source_url 'https://github.com/mauroseb/ice_motd'
